### ISSUE TITLE
Fix travis CI configuration to work with PhantomJS 1.9.17

### ISSUE THREAD

**Issue by eavgerinos** [skroutz/selectorablium#9]

**Comment by Zorbash** [comment]
Why should we have travis use phantomJS@1.9.17?

The current [broken master](https://travis-ci.org/skroutz/selectorablium/builds/66181457) seems related to https://github.com/billtrik/karma-fixture/issues/10 and https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/pull/3 issues.

**Comment by billtrik** [comment]
I should get to work (hello everyone!)

**Comment by Zorbash** [comment]
Using [`karma-fixture`@0.2.5](https://github.com/billtrik/karma-fixture) with the [karma-json-fixtures-preprocessor@0.0.4](https://github.com/dmitriiabramov/karma-json-fixtures-preprocessor/commit/44551e0db3007b77ccf6f929b2ccd2ed5a5b56d8) according to the readme of karma-fixture seems to solve the problem for now. Closing the issue.
